version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: StackApplication
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./packages/backend/.env.local:/app/packages/backend/.env.local
